import { FormEvent, useState } from 'react';
import { Link, Route, Routes, useNavigate } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import { ArrowRight, BadgeCheck, CalendarDays, Check, ChevronRight, LockKeyhole, Plus, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';

const api=axios.create({baseURL:import.meta.env.VITE_API_URL || '/api',withCredentials:true});
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const err=(e:any)=>e.response?.data?.error || 'Something went wrong. Please try again.';
function useMe(){return useQuery({queryKey:['me'],queryFn:()=>api.get('/auth/me').then(r=>r.data.user),retry:false});}
function Brand(){return <Link className="brand" to="/"><span>✦</span> SplitSub</Link>}
function Nav(){const {data:user}=useMe();return <header><Brand/><nav><Link to="/explore">Explore</Link><a href="/#how">How it works</a><Link to="/subscriptions">My subscriptions</Link></nav><div className="nav-actions">{user?<span className="text-link">Hi, {user.name.split(' ')[0]}</span>:<Link className="text-link" to="/login">Log in</Link>}<Link className="button small" to="/create"><Plus size={16}/> Create group</Link></div></header>}
function GroupCard({g}:{g:any}){const nav=useNavigate(),client=useQueryClient();const [message,setMessage]=useState('');const base=Number(g.totalPrice)/g.totalMembers,fee=Math.round(base*.04+5);async function join(){try{await api.post(`/groups/${g.id}/reserve`);setMessage('Slot reserved for 10 minutes. Payment checkout will be enabled when a payment provider is connected.');client.invalidateQueries({queryKey:['groups']});}catch(e){if((e as any).response?.status===401)nav('/login');else setMessage(err(e));}}return <article className="group-card"><div className="group-top"><div className="logo">{g.service.name[0]}</div><div><p className="eyebrow">{g.service.name}</p><h3>{g.plan.name}</h3></div><span className="slot">{g.availableSlots} slots left</span></div><div className="owner"><span className="avatar">{g.owner.name[0]}</span><span>Hosted by {g.owner.name}</span>{g.owner.emailVerified&&<BadgeCheck size={16}/>}</div><div className="price-row"><div><small>Monthly share</small><strong>{money(base)}</strong></div><div><small>Platform fee</small><b>{money(fee)}</b></div><div><small>Total payable</small><strong>{money(base+fee)}</strong></div></div><div className="card-foot"><span><CalendarDays size={15}/> Renews {new Date(g.renewalDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span><button onClick={join} className="button dark">Join group <ArrowRight size={16}/></button></div>{message&&<p className="form-message">{message}</p>}</article>}
function Home(){const {data=[]}=useQuery({queryKey:['groups'],queryFn:()=>api.get('/groups').then(r=>r.data)});return <><Nav/><main><section className="hero"><div className="pill"><Sparkles size={14}/> Fair sharing, built for peace of mind</div><h1>Share the cost.<br/><i>Enjoy more.</i></h1><p>Join eligible subscription groups and pay only your share. Clear pricing, protected payments, no credential sharing.</p><div className="hero-actions"><Link className="button" to="/explore">Explore groups <ArrowRight size={17}/></Link><Link className="secondary" to="/create">Create a group</Link></div><div className="trust"><span><ShieldCheck/> Terms-aware groups</span><span><LockKeyhole/> Secure checkout</span><span><Users/> Member invitations only</span></div></section><section className="section"><div className="section-head"><div><p className="eyebrow">EXPLORE NOW</p><h2>Great plans. Better together.</h2></div><Link to="/explore" className="inline">View all groups <ChevronRight size={18}/></Link></div>{data.length?<div className="grid">{data.slice(0,3).map((g:any)=><GroupCard key={g.id} g={g}/>)}</div>:<p className="empty">No groups yet. Be the first to create an eligible subscription group.</p>}</section></main><footer><Brand/><p>Made for fairer subscriptions.</p></footer></>}
function Explore(){const {data=[],isLoading}=useQuery({queryKey:['groups'],queryFn:()=>api.get('/groups').then(r=>r.data)});return <><Nav/><main className="page"><p className="eyebrow">MARKETPLACE</p><h1 className="page-title">Find your next subscription.</h1><div className="search"><Search size={19}/><input placeholder="Search groups"/></div><div className="results-head"><span>{data.length} groups available</span></div>{isLoading?<p>Loading groups…</p>:data.length?<div className="grid">{data.map((g:any)=><GroupCard key={g.id} g={g}/>)}</div>:<p className="empty">No open groups right now. Create one to get started.</p>}</main></>}
function Create(){const nav=useNavigate(),client=useQueryClient(),{data:services=[]}=useQuery({queryKey:['services'],queryFn:()=>api.get('/services').then(r=>r.data)});const [serviceId,setServiceId]=useState(''),[planId,setPlanId]=useState(''),[price,setPrice]=useState(''),[members,setMembers]=useState(''),[slots,setSlots]=useState(''),[message,setMessage]=useState('');const service=services.find((x:any)=>x.id===serviceId),plans=service?.plans||[];async function submit(e:FormEvent){e.preventDefault();try{await api.post('/groups',{serviceId,planId,totalPrice:Number(price),billingCycle:'MONTHLY',totalMembers:Number(members),offeredSlots:Number(slots),renewalDate:new Date(Date.now()+30*86400000).toISOString(),acceptedTerms:true});client.invalidateQueries({queryKey:['groups']});nav('/explore');}catch(e){setMessage(err(e));}}return <><Nav/><main className="create"><p className="eyebrow">CREATE A GROUP</p><h1>Start sharing, the right way.</h1><p>Only list plans that support official additional-member invitations.</p><form className="form-card" onSubmit={submit}><h2>Group details</h2><label>Service<select required value={serviceId} onChange={e=>{setServiceId(e.target.value);setPlanId('')}}><option value="">Select a service</option>{services.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Plan<select required disabled={!serviceId} value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Select a plan</option>{plans.map((p:any)=><option key={p.id} value={p.id}>{p.name} (up to {p.maxMembers})</option>)}</select></label><label>Total monthly subscription price (INR)<input required type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Total allowed members<input required type="number" min="2" value={members} onChange={e=>setMembers(e.target.value)}/></label><label>Slots offered<input required type="number" min="1" value={slots} onChange={e=>setSlots(e.target.value)}/></label>{message&&<p className="form-message">{message}</p>}<div className="form-actions"><span>By publishing, you accept the platform terms.</span><button className="button">Publish group <ArrowRight size={16}/></button></div></form></main></>}
function Login(){const nav=useNavigate(),client=useQueryClient(),[register,setRegister]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();try{if(register)await api.post('/auth/register',{name,email,password});await api.post('/auth/login',{email,password});await client.invalidateQueries({queryKey:['me']});nav('/create');}catch(e){setMessage(err(e));}}return <main className="auth"><Brand/><form className="auth-card" onSubmit={submit}><p className="eyebrow">{register?'CREATE ACCOUNT':'WELCOME BACK'}</p><h1>{register?'Join SplitSub.':'Good to see you.'}</h1><p>{register?'Create an account to host or join eligible groups.':'Log in to reserve a subscription slot.'}</p>{register&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)} /></label>}<label>Email<input required value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input required value={password} onChange={e=>setPassword(e.target.value)} minLength={10} type="password"/></label>{message&&<p className="form-message">{message}</p>}<button className="button">{register?'Create account':'Log in'} <ArrowRight size={16}/></button><small>{register?'Already have an account?':'New to SplitSub?'} <button type="button" className="link-button" onClick={()=>setRegister(!register)}>{register?'Log in':'Create an account'}</button></small></form></main>}
function Subscriptions(){const {data=[],isLoading}=useQuery({queryKey:['memberships'],queryFn:()=>api.get('/memberships/me').then(r=>r.data),retry:false});return <><Nav/><main className="page"><p className="eyebrow">MY SUBSCRIPTIONS</p><h1 className="page-title">Your memberships.</h1>{isLoading?<p>Log in to view subscriptions.</p>:data.length?<div className="grid">{data.map((m:any)=><GroupCard key={m.id} g={{...m.group,availableSlots:0}}/>)}</div>:<p className="empty">You have no memberships yet.</p>}</main></>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/explore" element={<Explore/>}/><Route path="/create" element={<Create/>}/><Route path="/login" element={<Login/>}/><Route path="/subscriptions" element={<Subscriptions/>}/><Route path="*" element={<Home/>}/></Routes>}
