import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import helmet from 'helmet'; import cors from 'cors'; import cookieParser from 'cookie-parser'; import rateLimit from 'express-rate-limit';
import { PrismaClient, GroupStatus, MembershipStatus, PaymentStatus } from '@prisma/client';
import jwt from 'jsonwebtoken'; import argon2 from 'argon2'; import { z } from 'zod'; import crypto from 'node:crypto';

const prisma = new PrismaClient(); const app = express();
const secret = process.env.JWT_SECRET || 'development-only-change-me';
const allowedOrigins = new Set([process.env.WEB_ORIGIN, 'http://localhost:5173', 'http://127.0.0.1:5173'].filter(Boolean));
app.use(helmet()); app.use(cors({
  origin: (origin: string | undefined, callback: (err: Error | null, allow?: boolean) => void) => {
    if (!origin || allowedOrigins.has(origin)) return callback(null, true);
    callback(new Error(`Origin ${origin} not allowed by CORS`));
  },
  credentials: true,
}));
app.use('/payments/webhook', express.raw({ type: 'application/json' })); app.use(express.json()); app.use(cookieParser());
app.use(rateLimit({ windowMs: 15 * 60_000, limit: 200, standardHeaders: true }));
type AuthRequest = Request & { user?: { id:string; role:string } };
const asyncRoute=(fn:(req:any,res:Response,next:NextFunction)=>Promise<unknown>)=>(req:Request,res:Response,next:NextFunction)=>fn(req,res,next).catch(next);
const auth=(req:AuthRequest,res:Response,next:NextFunction)=>{ try { const t=req.cookies.session; if(!t) throw 0; req.user=jwt.verify(t,secret) as any; next(); } catch { res.status(401).json({error:'Authentication required'}); } };
const requireRole=(...roles:string[])=>(req:AuthRequest,res:Response,next:NextFunction)=>!req.user||!roles.includes(req.user.role)?res.status(403).json({error:'Forbidden'}):next();
const safeUser=(u:any)=>({id:u.id,name:u.name,email:u.email,role:u.role,emailVerified:u.emailVerified,avatar:u.avatar});
const fee=(base:number, config:{type:string;percentage:any;fixed:any})=>Number((config.type==='FIXED'?Number(config.fixed):config.type==='PERCENTAGE'?base*Number(config.percentage)/100:base*Number(config.percentage)/100+Number(config.fixed)).toFixed(2));

app.post('/auth/register', asyncRoute(async(req,res)=>{ const input=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),phone:z.string().optional()}).parse(req.body); const passwordHash=await argon2.hash(input.password); const user=await prisma.user.create({data:{...input,passwordHash}}); res.status(201).json({user:safeUser(user)}); }));
app.post('/auth/login', asyncRoute(async(req,res)=>{ const input=z.object({email:z.string().email(),password:z.string()}).parse(req.body); const user=await prisma.user.findUnique({where:{email:input.email}}); if(!user||!(await argon2.verify(user.passwordHash,input.password))) return res.status(401).json({error:'Invalid email or password'}); const token=jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'7d'}); res.cookie('session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',maxAge:604800000}); res.json({user:safeUser(user)}); }));
app.post('/auth/logout',(_,res)=>{res.clearCookie('session');res.status(204).end();});
app.get('/auth/me',auth,asyncRoute(async(req:AuthRequest,res)=>{const u=await prisma.user.findUnique({where:{id:req.user!.id}});res.json({user:safeUser(u)});}));
app.get('/services',asyncRoute(async(_,res)=>res.json(await prisma.subscriptionService.findMany({where:{enabled:true},include:{plans:{where:{enabled:true}}}}))));
app.get('/services/:id/plans',asyncRoute(async(req,res)=>res.json(await prisma.subscriptionPlan.findMany({where:{serviceId:req.params.id,enabled:true}}))));
app.get('/groups',asyncRoute(async(req,res)=>{ const groups=await prisma.subscriptionGroup.findMany({where:{status:GroupStatus.OPEN},include:{service:true,plan:true,owner:{select:{name:true,emailVerified:true}},memberships:{where:{status:{in:[MembershipStatus.ACTIVE,MembershipStatus.RESERVED,MembershipStatus.PAYMENT_PENDING]}}}},orderBy:{createdAt:'desc'}}); res.json(groups.map(g=>({...g,availableSlots:g.offeredSlots-g.memberships.length,memberships:undefined}))); }));
app.post('/groups',auth,asyncRoute(async(req:AuthRequest,res)=>{const d=z.object({serviceId:z.string(),planId:z.string(),totalPrice:z.number().positive(),billingCycle:z.string(),totalMembers:z.number().int().min(2),offeredSlots:z.number().int().min(1),renewalDate:z.coerce.date(),acceptedTerms:z.literal(true)}).parse(req.body); const { acceptedTerms: _acceptedTerms, ...groupInput }=d; const plan=await prisma.subscriptionPlan.findFirst({where:{id:d.planId,serviceId:d.serviceId,enabled:true},include:{service:true}}); if(!plan||!plan.service.sharingAllowed||d.totalMembers>plan.maxMembers||d.offeredSlots>=d.totalMembers) return res.status(400).json({error:'Plan is not eligible for this group configuration'}); const group=await prisma.subscriptionGroup.create({data:{...groupInput,ownerId:req.user!.id,status:GroupStatus.OPEN}});res.status(201).json(group);}));
app.post('/groups/:id/reserve',auth,asyncRoute(async(req:AuthRequest,res)=>{ const groupId=String(req.params.id),userId=req.user!.id; const expiresAt=new Date(Date.now()+10*60_000); const r=await prisma.$transaction(async tx=>{ await tx.$executeRaw`SELECT id FROM "SubscriptionGroup" WHERE id=${groupId} FOR UPDATE`; const group=await tx.subscriptionGroup.findUnique({where:{id:groupId}}); if(!group||group.status!==GroupStatus.OPEN) throw new Error('Group is unavailable'); const taken=await tx.membership.count({where:{groupId,status:{in:[MembershipStatus.ACTIVE,MembershipStatus.RESERVED,MembershipStatus.PAYMENT_PENDING]}}}); const reserved=await tx.slotReservation.count({where:{groupId,expiresAt:{gt:new Date()},NOT:{userId}}}); if(taken+reserved>=group.offeredSlots) throw new Error('No slots available'); return tx.slotReservation.upsert({where:{groupId_userId:{groupId,userId}},create:{groupId,userId,expiresAt},update:{expiresAt}}); }); res.status(201).json({reservationId:r.id,expiresAt:r.expiresAt}); }));
app.post('/payments/order',auth,asyncRoute(async(req:AuthRequest,res)=>{ const {groupId}=z.object({groupId:z.string()}).parse(req.body); const reservation=await prisma.slotReservation.findUnique({where:{groupId_userId:{groupId,userId:req.user!.id}}}); if(!reservation||reservation.expiresAt<new Date()) return res.status(409).json({error:'Reservation has expired'}); const group=await prisma.subscriptionGroup.findUniqueOrThrow({where:{id:groupId}}); const config=await prisma.platformFeeConfig.findFirst({where:{active:true},orderBy:{createdAt:'desc'}}) || {type:'FIXED',percentage:0,fixed:10}; const base=Number(group.totalPrice)/group.totalMembers, platformFee=fee(base,config); const membership=await prisma.membership.upsert({where:{groupId_userId:{groupId,userId:req.user!.id}},create:{groupId,userId:req.user!.id,status:MembershipStatus.PAYMENT_PENDING,baseShare:base,platformFee,total:base+platformFee},update:{status:MembershipStatus.PAYMENT_PENDING}}); const payment=await prisma.payment.create({data:{userId:req.user!.id,groupId,membershipId:membership.id,amount:base+platformFee,platformFee,provider:'placeholder',providerOrderId:`order_${crypto.randomUUID()}`}}); res.status(201).json({paymentId:payment.id,orderId:payment.providerOrderId,amount:payment.amount,currency:'INR'}); }));
app.post('/payments/webhook',asyncRoute(async(req,res)=>{ const signature=req.header('x-splitsub-signature'); const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from(JSON.stringify(req.body)); const expected=crypto.createHmac('sha256',process.env.PAYMENT_WEBHOOK_SECRET||'dev').update(raw).digest('hex'); if(!signature||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected))) return res.status(401).json({error:'Invalid signature'}); const event=JSON.parse(raw.toString()); if(event.type!=='payment.succeeded') return res.status(204).end(); await prisma.$transaction(async tx=>{const payment=await tx.payment.findUniqueOrThrow({where:{providerOrderId:event.orderId}}); if(payment.status===PaymentStatus.SUCCEEDED)return; await tx.membership.update({where:{id:payment.membershipId},data:{status:MembershipStatus.ACTIVE}}); await tx.payment.update({where:{id:payment.id},data:{status:PaymentStatus.SUCCEEDED,providerPaymentId:event.paymentId}}); await tx.slotReservation.deleteMany({where:{groupId:payment.groupId,userId:payment.userId}});});res.status(204).end();}));
app.get('/memberships/me',auth,asyncRoute(async(req:AuthRequest,res)=>res.json(await prisma.membership.findMany({where:{userId:req.user!.id},include:{group:{include:{service:true,plan:true,owner:{select:{name:true}}}}}}))));
app.get('/notifications',auth,asyncRoute(async(req:AuthRequest,res)=>res.json(await prisma.notification.findMany({where:{userId:req.user!.id},orderBy:{createdAt:'desc'}}))));
app.post('/reports',auth,asyncRoute(async(req:AuthRequest,res)=>{const d=z.object({groupId:z.string().optional(),reason:z.string().min(3),details:z.string().max(2000).optional()}).parse(req.body);res.status(201).json(await prisma.report.create({data:{...d,reporterId:req.user!.id}}));}));
app.get('/admin/dashboard',auth,requireRole('ADMIN'),asyncRoute(async(_,res)=>{const [users,groups,memberships,payments]=await Promise.all([prisma.user.count(),prisma.subscriptionGroup.count({where:{status:GroupStatus.OPEN}}),prisma.membership.count({where:{status:MembershipStatus.ACTIVE}}),prisma.payment.aggregate({where:{status:PaymentStatus.SUCCEEDED},_sum:{amount:true,platformFee:true}})]);res.json({users,groups,memberships,gtv:payments._sum.amount||0,revenue:payments._sum.platformFee||0});}));
app.use((err:any,_:Request,res:Response,_n:NextFunction)=>{if(err instanceof z.ZodError)return res.status(400).json({error:'Invalid request',issues:err.flatten()});console.error(err);res.status(err.message?.includes('slot')||err.message?.includes('unavailable')?409:500).json({error:err.message||'Internal server error'});});
async function seedCatalog() {
  const catalog=[['Spotify','spotify',[['Premium Family',179,6]]],['YouTube Premium','youtube-premium',[['Family',299,5]]],['Apple One','apple-one',[['Family',365,6]]],['Microsoft 365','microsoft-365',[['Family',819,6]]]] as const;
  for (const [name,slug,plans] of catalog) { const service=await prisma.subscriptionService.upsert({where:{slug},update:{enabled:true,sharingAllowed:true},create:{name,slug,sharingAllowed:true,eligibilityRules:'Only official provider invitations are permitted.',enabled:true}}); for(const [plan,price,maxMembers] of plans) if(!await prisma.subscriptionPlan.findFirst({where:{serviceId:service.id,name:plan}})) await prisma.subscriptionPlan.create({data:{serviceId:service.id,name:plan,price,billingCycle:'MONTHLY',maxMembers}}); }
}
seedCatalog().then(()=>app.listen(Number(process.env.PORT)||4000,()=>console.log('SplitSub API listening'))).catch(error=>{console.error('Catalog startup failed',error);process.exit(1);});
